### ISSUE TITLE
Add a github build workflow

### ISSUE THREAD

**Issue by mattleibow** [mattleibow/GitHubAutopilot#11]
Can you add a workflow that builds main and prs to main:

```
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install the .NET MAUI workload
        run: dotnet workload install maui-android

      - name: Run a build
        run: dotnet build
```
